var exchangeMap = new Map([
    ['TSX', 'TOR'], ['TOR', 'TOR'],
    ['PNK', 'PNK'], ['OTCMKTS','PNK'],
    ['NMS', 'NMS'], ['NASDAQ','NMS'], ['NDAQ','NMS'],
    ['NYQ', 'NYQ'], ['NYSE','NYQ'],
    ['KOE', 'KOE'], ['KOSDAQ','KOE'],
    ['IST', 'IST'], ['BIST','IST'],
    ['OTCBB','OBB'], ['OBB', 'OBB'],
    ['BCBA;','BUE'], ['BUE', 'BUE'],
    ['FWB','FRA'], ['FRA', 'FRA'],
    ['SEHK','HKG'], ['HKG', 'HKG'],
    ['SGX','SES'], ['SES', 'SES'],
    ['BSE', 'BSE'],
    ['LSE', 'LSE'],
    ['ASE', 'ASE'],
    ['JKT', 'JKT'],
    ['MEX', 'MEX'],
    ['KLS', 'KLS'],
    ['TWO', 'TWO'],
    ['DUS', 'DUS'],
    ['TAI', 'TAI'],
    ['BER', 'BER'],
    ['MUN', 'MUN'],
    ['EUX', 'EUX'],
    ['NSI', 'NSI'],
    ['ISE', 'ISE'],
    ['NCM', 'NCM'],
    ['GER', 'GER'],
    ['VAN', 'VAN'],
    ['STU', 'STU'],
    ['HAN', 'HAN'],
    ['DOH', 'DOH'],
    ['NGM', 'NGM'],
    ['ASX', 'ASX'],
    ['PAR', 'PAR'],
    ['STO', 'STO'],
    ['TLV', 'TLV'],
    ['MCE', 'MCE'],
    ['KSC', 'KSC'],
    ['EBS', 'EBS'],
    ['HAM', 'HAM'],
    ['SET', 'SET'],
    ['MCX', 'MCX'],
    ['SAO', 'SAO'],
    ['OSL', 'OSL'],
    ['ATH', 'ATH'],
    ['NZE', 'NZE'],
    ['VIE', 'VIE'],
    ['ICE', 'ICE'],
    ['MIL', 'MIL'],
    ['LIS', 'LIS'],
    ['AMS', 'AMS'],
    ['HEL', 'HEL'],
    ['CPH', 'CPH'],
    ['CCS', 'CCS'],
    ['BRU', 'BRU'],
    ['SHH', 'SHH'],
    ['IOB', 'IOB'],
    ['RIS', 'RIS'],
    ['PCX', 'PCX'],
    ['TLO', 'TLO'],
    ['VTX', 'VTX'],
    ['LIT', 'LIT'],
    ['BTS', 'BTS'],
    ['SSE', 'SSE']
  ]
);


/* These are left out as they only are used for index */
//exchangeMap.set('NYSE', 'NYSE');
//exchangeMap.set('NASDAQ', 'NASDAQ');
module.exports = exchangeMap;
